version: 5.5.1.2
type: payment
authorName: 'emerchantpay Ltd.'
moduleName: 'emerchantpay'
description: 'Accept payments through emerchantpay''s Payment Gateway - Genesis'
minorRequiredCoreVersion: 0
dependsOn: {  }
incompatibleWith: {  }
skins: {  }
showSettingsForm: false
canDisable: true
autoloader:
  - vendor/autoload.php
